trigger: none

pool:
  name: "windowspool"
  demands:
    - Agent.Name -equals windowsagent

variables:
  ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
  ARM_TENANT_ID: $(ARM_TENANT_ID)
  ARM_CLIENT_ID: $(ARM_CLIENT_ID)
  ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)


stages:
# Stage 1: Install Terraform
- stage: InstallTerraform
  displayName: "Install Terraform"
  jobs:
    - job: InstallTerraform
      displayName: "Install Terraform"
      steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'
        
        - task: CopyFiles@2
          inputs:
            SourceFolder: 'C:\vsts-agent-win-x64-3.246.0\_work\_tool\terraform\1.9.8\x64'
            Contents: '**/*'  # Copy all files in the directory
            TargetFolder: 'C:\terraform-software'

        # Add Terraform to PATH environment variable
        - powershell: |
            [System.Environment]::SetEnvironmentVariable("PATH", $env:PATH + ";C:\terraform-software", [System.EnvironmentVariableTarget]::Machine)
            echo "Updated PATH: $env:PATH"  # Optional: Print the PATH to verify it's correct
          displayName: "Add Terraform path to environment variables"
     
        # Publish Terraform installer as artifact for further jobs
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: 'C:\terraform-software'
            ArtifactName: 'terraform-software'


 # Stage 2: Get Terraform Code
- stage: GetTerraformCode
  displayName: "Get Terraform Code"
  jobs:
    - job: GetTerraformCode
      displayName: "Get Terraform Code"
      steps:
        # Checkout the Terraform code from repository
        - checkout: self

        # Publish the Terraform code as an artifact for later use
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: 'C:\vsts-agent-win-x64-3.246.0\_work\1\s'
            ArtifactName: 'terraform-code'
        
        # Download the Terraform code artifact for subsequent use
        - task: DownloadBuildArtifacts@1
          inputs:
            buildType: 'current'
            downloadType: 'single'
            artifactName: 'terraform-code'
            downloadPath: 'C:\'

# Stage 3: Run Terraform Init
- stage: RunTerraformCommands
  displayName: "Run Terraform Commands"
  jobs:
    - job: init
      displayName: "terraform init"
      steps:
        - task: DownloadBuildArtifacts@1
          inputs:
            buildType: 'current'
            artifactName: 'terraform-software'
            downloadPath: 'C:\terraform-software' 

        - task: TerraformTaskV4@4
          inputs:
            provider: 'azurerm'
            command: 'init'
            # workingDirectory: 'C:\terraform-code'  # Use the correct path where the code is now downloaded
            backendServiceArm: 'devops-azure-connection'
            backendAzureRmResourceGroupName: 'rg-terraform-backend'
            backendAzureRmStorageAccountName: 'terraformbackendstate1'
            backendAzureRmContainerName: 'tfstate-container'
            backendAzureRmKey: 'dev.terraform.tfstate'